version: '3.8'

services:
    aws:
        container_name: test-aws-sdk-aws
        image: localstack/localstack:0.13.0.10
        environment:
            LAMBDA_EXECUTOR: docker
            COMPOSE_CONVERT_WINDOWS_PATHS: 'true'
            LAMBDA_REMOTE_DOCKER: 'false'
            DATA_DIR: /tmp/localstack/data
        ports:
            - 4566:4566
        networks:
            - network
        volumes:
            - aws:/tmp/localstack
            - /var/run/docker.sock:/var/run/docker.sock
    php:
        container_name: test-aws-sdk-php
        image: php:8.1.0-apache
        ports:
            - 8080:80
        networks:
            - network
        volumes:
            - ./vendor:/var/www/vendor
            - ./php:/var/www/html
    nodejs:
        container_name: test-aws-sdk-nodejs
        image: node:17.2.0
        ports:
            - 8081:80
        networks:
            - network
        volumes:
            - .:/usr/src/app
        working_dir: /usr/src/app
        command: [ node, /usr/src/app/nodejs/index.mjs ]

networks:
    default:
        name: test-aws-sdk
    network:
        name: test-aws-sdk

volumes:
    aws:
        name: test-aws-sdk-aws
